### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by pperrot1** [NickNish09/vacinometro-brasil#1]
Oi, tudo bem?
Tem como você incluir um output file (csv, json, xls) para eu conecta-lo a um fluxo de Alteryx?

**Comment by NickNish09** [comment]
Pretendo fazer uma API json também em breve. Por enquanto o foco vai ser no front pra pegar esses dados e mostrar. Vou usar uns crawlers e faço essa API json já.

**Comment by pperrot1** [comment]
Muito obrigada!!!
Fico no aguardo!


Kind Regards,

[cid:image003.jpg@01D6EFE5.1B083400]
Paula Perrotta Assumpção
South America Strategy

"The information contained herein is FORD PROPRIETY information and may include FORD CONFIDENTIAL information as defined in Ford’s Global Information Standard II. Reproduction of this document, disclosure of the information, and use for any purpose other than the conduct of business with Ford is expressly prohibited. If the reader of the message is not the intended recipient, or the Agent responsible for delivering the e-mail and attachment to the intended recipient, you are hereby notified that dissemination, distribution or copying of this communication is prohibited. In this circumstance please reply to this e-mail and highlight the error."

**Comment by NickNish09** [comment]
API disponível. Basta entrar no endpoint:
`https://vacinometro.com/api/districts/<codigo_do_estado>` que ele trás as informações

Ex:
`https://vacinometro.com/api/districts/sp` pra pegar as informações de SP

Para pegar do Brasil todo, use o código do estado "total":

`https://vacinometro.com/api/districts/total`

Colocarei isso na documentação.

**Comment by pperrot1** [comment]
Muito legal!! Obrigada!!!
